name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app
    
    - name: Build and Test
      run: |
        xcodebuild test \
          -project VIPER-Boilerplate.xcodeproj \
          -scheme "VIPER-Boilerplate" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
